<?php
if (!defined("PJ_HOST")) define("PJ_HOST", "localhost");
if (!defined("PJ_USER")) define("PJ_USER", "uploadvehicles_rfeder5434");
if (!defined("PJ_PASS")) define("PJ_PASS", "{.f-I-?0A{2(");
if (!defined("PJ_DB")) define("PJ_DB", "uploadvehicles_Dtbss9");
if (!defined("PJ_PREFIX")) define("PJ_PREFIX", "");
if (!defined("PJ_INSTALL_FOLDER")) define("PJ_INSTALL_FOLDER", "/");
if (!defined("PJ_INSTALL_PATH")) define("PJ_INSTALL_PATH", "/home/uploadvehicles/public_html/");
if (!defined("PJ_INSTALL_URL")) define("PJ_INSTALL_URL", "https://www.uploadvehicles.com/");
if (!defined("PJ_SALT")) define("PJ_SALT", "Z8LKUYEA");
if (!defined("PJ_INSTALLATION")) define("PJ_INSTALLATION", "MjYwODUyOTcwMTE3NDU2MTQ1MzA5NzcyNTE5MTUwMDgxNDQ0NzA2ODg1NTUxMDIwOTExNDU0OTA1MTA5NjAyMjk5MTEzNjU3MDc2MjA0NzEyMTQ4ODMwNDk0Njk5ODA4Mjg0IDE4NDkzMTY0NzIzODM5MDM2NDQ2ODU1MTY3MzkzNDc4NzU0NDQ0MjUyNTcwNjA5NDkxMzE3ODUzMDYwMjg3NTA0OTQyMTY2OTc3NzI1NjgyODk3NjA1MDQ2MDgyNzIwMjM2NSAxMDk2NTQ3NzM2NTUyMDU5MzgzNjExMDAzNzU1Mjg2MjAxOTE5MzE4MDQ5MDEzODQzODI1MTQ2NjQ0NTU0NzgzMDQ3Mzk1OTc0OTkzMDM1MTQxMjg3NTUxNzE0MTMxOTc4NDg5IDEyMTgwNjMyODAyODY5NjQ5MjU5OTM4MDEzMDIxMTM0NjQwMjM0MjIzODI2Nzg3MjkxMjU3Mjc4NDU1MjY5MTA2NDQ2MzM2MDAwOTkwNjMwNTkzMjA0Njk5MDEzNjIxNTc3MzQgNDc0NTg0NjAyNzEyNDY0Njg4ODk5OTI0MDI3NDYyNTI0MzU3NTUzODE3NDgyMTgxMzkwMjAwOTE3NzYzNDQwNzg2MTE0MTgyMDgzNzY1NTAyMzQzNzg2NTg5NzIyNDQ5NzE4IDE2MzUyMzczODkwMTc5MTU2MzkxNzE4MDY1ODQ1NDUyNTA5MjY4NTU2NDk3MjIyODQ5Nzk5NDMyNDgxODAzODQyODY2NjI5NDk4OTQwNjczNDI3NzIzNTYwMzE4Njg0MTEzMA==");
?>